### ISSUE TITLE
org.jboss.reddeer.eclipse.test.ui.views.log.LogViewTest.getErrorMessage default

### ISSUE THREAD

**Issue by jpeterka** [jboss-reddeer/reddeer#1165]
Please analyze and provide fix preventing widget is disposed during further processing.

org.jboss.reddeer.eclipse.test.ui.views.log.LogViewTest.getErrorMessage default

Error Message

Exception during sync execution in UI thread
Stacktrace

org.jboss.reddeer.core.exception.CoreLayerException: Exception during sync execution in UI thread
	at org.jboss.reddeer.core.util.Display.syncExec(Display.java:86)
	at org.jboss.reddeer.core.handler.TreeItemHandler.isExpanded(TreeItemHandler.java:90)
	at org.jboss.reddeer.core.handler.TreeItemHandler$TreeHeardExpandNotification.test(TreeItemHandler.java:416)
	at org.jboss.reddeer.common.wait.WaitUntil.stopWaiting(WaitUntil.java:57)
	at org.jboss.reddeer.common.wait.AbstractWait.wait(AbstractWait.java:108)
	at org.jboss.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:77)
	at org.jboss.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:53)
	at org.jboss.reddeer.common.wait.WaitUntil.<init>(WaitUntil.java:37)
	at org.jboss.reddeer.core.handler.TreeItemHandler.expand(TreeItemHandler.java:368)
	at org.jboss.reddeer.swt.impl.tree.AbstractTreeItem.expand(AbstractTreeItem.java:94)
	at org.jboss.reddeer.swt.impl.tree.AbstractTreeItem.getItems(AbstractTreeItem.java:188)
	at org.jboss.reddeer.swt.impl.tree.AbstractTree.getAllItemsRecursive(AbstractTree.java:82)
	at org.jboss.reddeer.swt.impl.tree.AbstractTree.getAllItems(AbstractTree.java:33)
	at org.jboss.reddeer.eclipse.ui.views.log.LogView.getErrorMessages(LogView.java:106)
	at org.jboss.reddeer.eclipse.test.ui.views.log.LogViewTest.getErrorMessage(LogViewTest.java:128)
Caused by: org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4491)
	at org.eclipse.swt.SWT.error(SWT.java:4406)
	at org.eclipse.swt.SWT.error(SWT.java:4377)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:482)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:419)
	at org.eclipse.swt.widgets.TreeItem.getExpanded(TreeItem.java:548)
	at org.jboss.reddeer.core.handler.TreeItemHandler$3.run(TreeItemHandler.java:94)
	at org.jboss.reddeer.core.handler.TreeItemHandler$3.run(TreeItemHandler.java:1)
	at org.jboss.reddeer.core.util.Display$ErrorHandlingRunnable.run(Display.java:159)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3794)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3433)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclipse.tycho.surefire.osgibooter.UITestApplication.runApplication(UITestApplication.java:31)
	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.run(AbstractUITestApplication.java:120)
	at org.eclipse.tycho.surefire.osgibooter.UITestApplication.start(UITestApplication.java:37)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)

**Comment by jrichter1** [comment]
As far as I can tell, this seems to happen when a TreeItem gets disposed somewhere in between being retrieved and expanded. This then causes the exception in TreeItemHandler#expand when first checks if the item is expanded by item.getExpanded(). The fix should stop propagating the errors if the item is disposed.
