### ISSUE TITLE
SIGSEGV when running BrowserTest on Ubuntu

### ISSUE THREAD

**Issue by jpeterka** [jboss-reddeer/reddeer#1233]
System: Ubuntu/Mint 17.1 64 bit
Steps: mvn clean install -Dtest=BrowserTest 

 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007f3843f0206c, pid=19636, tid=139877124200192

 JRE version: Java(TM) SE Runtime Environment (8.0_45-b14) (build 1.8.0_45-b14)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.45-b02 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 V  [libjvm.so+0x4a706c][thread 139878805292800 also had an error]
  CompileBroker::compile_method(methodHandle, int, int, methodHandle, int, char const*, Thread*)+0x1bc

 Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

 An error report file with more information is saved as:
 /home/jpeterka/data/repo/github.com/jpeterka/reddeer/tests/org.jboss.reddeer.swt.test/hs_err_pid19636.log

 If you would like to submit a bug report, please visit:
   http://bugreport.java.com/bugreport/crash.jsp

**Comment by jpeterka** [comment]
Adding -DplatformSystemProperties="-Dorg.eclipse.swt.browser.DefaultType=mozilla" prevents from JVM Crash, now there is this issue:
```
evaluateTest default(org.jboss.reddeer.swt.test.impl.browser.BrowserTest)  Time elapsed: 0.075 sec  <<< ERROR!
org.eclipse.swt.SWTException: Failed to execute runnable (org.eclipse.swt.SWTError: No more handles [Could not detect registered XULRunner to use])
	at org.eclipse.swt.SWT.error(SWT.java:4517)
	at org.eclipse.swt.browser.Mozilla.create(Mozilla.java:683)
	at org.eclipse.swt.browser.Browser.<init>(Browser.java:99)
	at org.jboss.reddeer.swt.test.impl.browser.BrowserTest$TestBrowser.<init>(BrowserTest.java:98)
	at org.jboss.reddeer.swt.test.impl.browser.BrowserTest.createControls(BrowserTest.java:28)
```

**Comment by jpeterka** [comment]
All right, after multiple testing, I have working solution for this issue
```
mvn clean install -Dtest=BrowserTest -DplatformSystemProperties="-Dorg.eclipse.swt.browser.DefaultType=mozilla -Dorg.eclipse.swt.browser.XULRunnerPath=/home/jpeterka/ide/test/jbds/studio/plugins/org.mozilla.xulrunner.gtk.linux.x86_64_1.9.2.19pre/xulrunner"
```
Finally test is processing, however it ends with another (expectable) error #1232 but at least this issue can be closed.
