### ISSUE TITLE
org.jboss.reddeer.eclipse.test.ui.views.properties.TabbedPropertiesTest.selectTabTest is failing

### ISSUE THREAD

**Issue by jpeterka** [jboss-reddeer/reddeer#1235]
http://machydra.brq.redhat.com:8080/job/RedDeer_master_matrix/jdk=sunjdk1.7,label=orion64/670/testReport/junit/org.jboss.reddeer.eclipse.test.ui.views.properties/TabbedPropertiesTest/selectTabTest_default/?

Error Message

Timeout after: 10 s.: shell with text matching"Java - Eclipse Platform" is active
Stacktrace

org.jboss.reddeer.common.exception.WaitTimeoutExpiredException: Timeout after: 10 s.: shell with text matching"Java - Eclipse Platform" is active
	at org.jboss.reddeer.common.wait.AbstractWait.timeoutExceeded(AbstractWait.java:159)
	at org.jboss.reddeer.common.wait.AbstractWait.wait(AbstractWait.java:112)
	at org.jboss.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:77)
	at org.jboss.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:53)
	at org.jboss.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:41)
	at org.jboss.reddeer.common.wait.WaitUntil.<init>(WaitUntil.java:25)
	at org.jboss.reddeer.swt.impl.shell.AbstractShell.setFocus(AbstractShell.java:53)
	at org.jboss.reddeer.workbench.impl.shell.WorkbenchShell.<init>(WorkbenchShell.java:24)
	at org.jboss.reddeer.workbench.impl.view.AbstractView.isOpened(AbstractView.java:253)
	at org.jboss.reddeer.workbench.impl.view.AbstractView.getViewCTabItem(AbstractView.java:120)
	at org.jboss.reddeer.workbench.impl.view.AbstractView.<init>(AbstractView.java:74)
	at org.jboss.reddeer.workbench.impl.view.AbstractView.<init>(AbstractView.java:61)
	at org.jboss.reddeer.workbench.impl.view.WorkbenchView.<init>(WorkbenchView.java:21)
	at org.jboss.reddeer.eclipse.jdt.ui.AbstractExplorer.<init>(AbstractExplorer.java:35)
	at org.jboss.reddeer.eclipse.jdt.ui.ProjectExplorer.<init>(ProjectExplorer.java:15)
	at org.jboss.reddeer.eclipse.test.ui.views.properties.TabbedPropertiesTest.openXsdFile(TabbedPropertiesTest.java:67)

**Comment by ljelinkova** [comment]
Duplicate to #1245
