### ISSUE TITLE
org.jboss.reddeer.eclipse.test.jdt.EnumWizardTest.createEnumClass is failing

### ISSUE THREAD

**Issue by jpeterka** [jboss-reddeer/reddeer#1236]
http://machydra.brq.redhat.com:8080/job/RedDeer_master_matrix/jdk=sunjdk1.7,label=winos7_32b/670/testReport/junit/org.jboss.reddeer.eclipse.test.jdt/EnumWizardTest/createEnumClass_default/?

org.jboss.reddeer.eclipse.test.jdt.EnumWizardTest.createEnumClass default

Failing for the past 1 build (Since Failed#670 )
Took 19 sec.
edit description
Error Message

Timeout after: 10 s.: shell with text matching"New Java Project" is active
Stacktrace

org.jboss.reddeer.common.exception.WaitTimeoutExpiredException: Timeout after: 10 s.: shell with text matching"New Java Project" is active
	at org.jboss.reddeer.common.wait.AbstractWait.timeoutExceeded(AbstractWait.java:159)
	at org.jboss.reddeer.common.wait.AbstractWait.wait(AbstractWait.java:112)
	at org.jboss.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:77)
	at org.jboss.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:53)
	at org.jboss.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:41)
	at org.jboss.reddeer.common.wait.WaitWhile.<init>(WaitWhile.java:24)
	at org.jboss.reddeer.eclipse.jdt.ui.ide.NewJavaProjectWizardDialog.finish(NewJavaProjectWizardDialog.java:64)
	at org.jboss.reddeer.eclipse.jdt.ui.ide.NewJavaProjectWizardDialog.finish(NewJavaProjectWizardDialog.java:29)
	at org.jboss.reddeer.eclipse.test.jdt.EnumWizardTest.createEnumClass(EnumWizardTest.java:25)
Standard Output

**Comment by rawagner** [comment]
Two Eclipse instances were running on the same slave - i guess this must have had some effect on running tests. Creating enum is a simple operation so I don't think its necessary to raise timeout from default 10s to something higher. And also it didn't happen again for quite a long time.
