### ISSUE TITLE
org.jboss.reddeer.eclipse.test.datatools.ui.ResultViewTest.testSQLResultViewSuccess failed

### ISSUE THREAD

**Issue by jpeterka** [jboss-reddeer/reddeer#1238]
http://machydra.brq.redhat.com:8080/job/RedDeer_master_matrix/jdk=sunjdk1.7,label=domek/671/testReport/junit/org.jboss.reddeer.eclipse.test.datatools.ui/ResultViewTest/testSQLResultViewSuccess_default/?

org.jboss.reddeer.eclipse.test.datatools.ui.ResultViewTest.testSQLResultViewSuccess default

Failing for the past 1 build (Since Failed#671 )
Took 1 min 15 sec.
edit description
Error Message

Timeout after: 10 s.: tree has children
Stacktrace

org.jboss.reddeer.common.exception.WaitTimeoutExpiredException: Timeout after: 10 s.: tree has children
	at org.jboss.reddeer.common.wait.AbstractWait.timeoutExceeded(AbstractWait.java:159)
	at org.jboss.reddeer.common.wait.AbstractWait.wait(AbstractWait.java:112)
	at org.jboss.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:77)
	at org.jboss.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:53)
	at org.jboss.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:41)
	at org.jboss.reddeer.common.wait.WaitWhile.<init>(WaitWhile.java:24)
	at org.jboss.reddeer.eclipse.datatools.sqltools.result.ui.ResultView.removeAllResults(ResultView.java:61)
	at org.jboss.reddeer.eclipse.test.datatools.ui.ResultViewTest.removeResults(ResultViewTest.java:214)
	at org.jboss.reddeer.eclipse.test.datatools.ui.ResultViewTest.testSQLResultView(ResultViewTest.java:183)
	at org.jboss.reddeer.eclipse.test.datatools.ui.ResultViewTest.testSQLResultViewSuccess(ResultViewTest.java:178)

**Comment by jpeterka** [comment]
Seems to be fixed by other RedDeer updates
