### ISSUE TITLE
org.jboss.reddeer.eclipse.test.wst.server.ui.view.ServerTest.publish failed

### ISSUE THREAD

**Issue by jpeterka** [jboss-reddeer/reddeer#1278]
http://machydra.brq.redhat.com:8080/job/RedDeer_master_matrix/jdk=sunjdk1.7,label=winos7_32b/715/testReport/junit/org.jboss.reddeer.eclipse.test.wst.server.ui.view/ServerTest/publish_default/?

Error Message

Expected: is <SYNCHRONIZED>
     but: was <PUBLISHING>
Stacktrace

java.lang.AssertionError: 
Expected: is <SYNCHRONIZED>
     but: was <PUBLISHING>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at org.jboss.reddeer.eclipse.test.wst.server.ui.view.ServerTest.publish(ServerTest.java:180)
Standard Output

**Comment by ljelinkova** [comment]
This test has failed on slave that is not part verification job slaves matrix.
