### ISSUE TITLE
org.jboss.reddeer.eclipse.test.wst.server.ui.view.ServersViewTest.getServers failed

### ISSUE THREAD

**Issue by jpeterka** [jboss-reddeer/reddeer#1322]
http://machydra.brq.redhat.com:8080/job/RedDeer_master_matrix/jdk=sunjdk1.7,label=stable-windows/755/testReport/junit/org.jboss.reddeer.eclipse.test.wst.server.ui.view/ServersViewTest/getServers_default/

Error Message

There are no items matching matcher tree item text on position <0> matches "Test server"
Stacktrace

org.jboss.reddeer.core.exception.CoreLayerException: There are no items matching matcher tree item text on position <0> matches "Test server"
	at org.jboss.reddeer.core.lookup.TreeItemLookup.getTreeItems(TreeItemLookup.java:122)
	at org.jboss.reddeer.core.lookup.TreeItemLookup.getTreeItems(TreeItemLookup.java:74)
	at org.jboss.reddeer.core.lookup.TreeItemLookup.getTreeItem(TreeItemLookup.java:53)
	at org.jboss.reddeer.swt.impl.tree.DefaultTreeItem.<init>(DefaultTreeItem.java:37)
	at org.jboss.reddeer.swt.impl.tree.DefaultTreeItem.<init>(DefaultTreeItem.java:27)
	at org.jboss.reddeer.eclipse.wst.server.ui.wizard.NewServerWizardPage.selectType(NewServerWizardPage.java:26)
	at org.jboss.reddeer.eclipse.test.wst.server.ui.view.ServersViewTestCase.createServer(ServersViewTestCase.java:61)
	at org.jboss.reddeer.eclipse.test.wst.server.ui.view.ServersViewTest.getServers(ServersViewTest.java:44)

**Comment by jpeterka** [comment]
@jrichter1 what's the status here?

**Comment by jpeterka** [comment]
@jrichter1 please join PR with issue next time

**Comment by rawagner** [comment]
PR applied to master
